package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComVamos1978springPetclinicGitRefsHeadsMaster1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComVamos1978springPetclinicGitRefsHeadsMaster1")
    name = "https://github.com/vamos1978/spring-petclinic.git#refs/heads/master (1)"
    url = "https://github.com/vamos1978/spring-petclinic.git"
    authMethod = password {
        userName = "vamos1978"
        password = "credentialsJSON:7f9c4492-a86b-4c69-9dbd-9c7d36c695e6"
    }
}))

